### ISSUE TITLE
0.100.1更新后无法加载common timer

### ISSUE THREAD

**Issue by nichwang88** [cnk700i/common_timer#3]
首先感谢作者发布该插件，挺好用的，我一直在用。

今天更新了HA最新版本0.100.1，不知为何一直出现配置错误，之前版本都好正常使用的，烦请作者帮忙查看，多谢。
PS: input_select、input_text、input_boolean组件我也重新导入修改过，依然无效，删除也依然报错。

Setup failed for common_timer: Invalid config.

Unable to import common_timer: cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' (/usr/src/homeassistant/homeassistant/util/async_.py)

**Comment by kukudemajia** [comment]
25行代码注释掉就可以了，这行是废码
# from homeassistant.util.async_ import (run_coroutine_threadsafe, run_callback_threadsafe)

**Comment by nichwang88** [comment]
更新后搞定了，多谢！！！
