### ISSUE TITLE
针对HA version: 0.100.2提交了PR，同时提个功能需求

### ISSUE THREAD

**Issue by kukudemajia** [cnk700i/common_timer#5]
#4 针对HA version: 0.100.2出现的问题修正；
这个通用定时器很不错，希望能继续完善。
目前遇到的问题就是对于同一设备不能做多个定时
比如我要求风扇2分钟后开启，十五分钟后关闭
目前只要设置了一条定时规则以后，再次选择该设置就只能显示倒计时，无法新增，只有修改原有的规则，逻辑上是否应该考虑更全面一些呢？
非常感谢

**Comment by cnk700i** [comment]
谢谢提建议，其实很早有计划做多规则的，只是前端展示交互这块不好实现，感觉改HA前端好复杂，不会=。=

**Comment by kukudemajia** [comment]
> 谢谢提建议，其实很早有计划做多规则的，只是前端展示交互这块不好实现，感觉改HA前端好复杂，不会=。=

其实现在的组件已经做得不错了，可以发到HA社区看看是否有人可以继续开发
